basePath: /api/v1
definitions:
  main.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  main.User:
    properties:
      age:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: This is a sample server
  termsOfService: http://example.com/terms/
  title: Example API
  version: "1.0"
paths:
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Get user information by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Get User
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create a new user with provided information
      parameters:
      - description: User Information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Create User
      tags:
      - user
swagger: "2.0"
